server:
  port: 8081

spring:
  application:
    name: Card-Microservice
  datasource:
    url: jdbc:postgresql://localhost:5432/{database}
    username: {username} }
    password: {password}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
