server:
  port: 8083

spring:
  application:
    name: Loan-Microservice
  datasource:
    url: jdbc:postgresql://localhost:5432/vaultix
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
